/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include "libavcodec/avcodec.h"
#include "libavformat/avformat.h"
#include "libavfilter/avfilter.h"
/* Header for class cn_yunyunhei_wuhang_simplest_ffmpeg_android_helloworld_NdkJniUtils */

#ifndef _Included_cn_yunyunhei_wuhang_simplest_ffmpeg_android_helloworld_NdkJniUtils
#define _Included_cn_yunyunhei_wuhang_simplest_ffmpeg_android_helloworld_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yunyunhei_wuhang_simplest_ffmpeg_android_helloworld_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_yunyunhei_wuhang_simplest_1ffmpeg_1android_1helloworld_NdkJniUtils_getCLanguageString
  (JNIEnv *, jobject);

/*
 * Class:     cn_yunyunhei_wuhang_simplest_ffmpeg_android_helloworld_NdkJniUtils
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_yunyunhei_wuhang_simplest_1ffmpeg_1android_1helloworld_NdkJniUtils_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     cn_yunyunhei_wuhang_simplest_ffmpeg_android_helloworld_NdkJniUtils
 * Method:    unimplementedStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_yunyunhei_wuhang_simplest_1ffmpeg_1android_1helloworld_NdkJniUtils_unimplementedStringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
